# pretrained_text_encoder_path: t2i_models/FLUX/FLUX.1-dev/text_encoder/model.safetensors
# pretrained_text_encoder_2_path: t2i_models/FLUX/FLUX.1-dev/text_encoder_2
pretrained_dit_path: /mnt/nas1/zhanghong/project/DiffSynth-Studio/models/stepfun-ai/Step1X-Edit/step1x-edit-i1258.safetensors
pretrained_vae_path: t2i_models/FLUX/FLUX.1-dev/ae.safetensors
dataset_path: 'data/all2all/embed/image_pulse/image_embeds_252_image_pulse.jsonl'
output_path: workdirs/decoder/train
height: 512
width: 512
dataloader_num_workers: 1
learning_rate: 0.00001
use_gradient_checkpointing: True
accumulate_grad_batches: 16
batch_size: 1
training_strategy: 'deepspeed_stage_3'
precision: 'bf16'
steps_per_epoch: 64000
max_epochs: 10
lr_warmup_steps: 500
use_wandb: True
wandb_api_key: 4bc3aa1826820be83c7e7ee086cf7256f7d40924
