pretrained_text_encoder_path: /mnt/nas1/zhanghong/project/DiffSynth-Studio/models/FLUX/FLUX.1-dev/text_encoder/model.safetensors
pretrained_text_encoder_2_path: /mnt/nas1/zhanghong/project/DiffSynth-Studio/models/FLUX/FLUX.1-dev/text_encoder_2
pretrained_dit_path: /mnt/nas1/zhanghong/project/DiffSynth-Studio/models/FLUX/FLUX.1-dev/flux1-dev.safetensors
pretrained_vae_path: /mnt/nas1/zhanghong/project/DiffSynth-Studio/models/FLUX/FLUX.1-dev/ae.safetensors
dataset_path: 'data/all2all/embed/high_quality_252_embed.jsonl'
output_path: workdirs/decoder/train
height: 512
width: 512
dataloader_num_workers: 12
learning_rate: 0.00001
use_gradient_checkpointing: True
accumulate_grad_batches: 16
batch_size: 1
training_strategy: 'deepspeed_stage_3'
precision: 'bf16'
steps_per_epoch: 6400
max_epochs: 10
lr_warmup_steps: 500
load_from: 'models/Nexus-Gen/decoder_81_512.bin'
